mod commands;
mod server;

use tauri::{
    menu::{Menu, MenuItem},
    tray::TrayIconBuilder,
    Emitter, Manager,
};

/// Dragging to a screen edge triggers Windows snapping (Aero Snap / Win11 snap
/// layouts) because the drag runs the system title-bar move loop. Windows only
/// snap-snaps windows that are maximizable, so clearing WS_MAXIMIZEBOX opts this
/// window out entirely — our own setPosition/setSize docking is unaffected.
#[cfg(windows)]
fn disable_aero_snap(window: &tauri::WebviewWindow) {
    const GWL_STYLE: i32 = -16;
    const WS_MAXIMIZEBOX: isize = 0x0001_0000;
    #[link(name = "user32")]
    extern "system" {
        fn GetWindowLongPtrW(hwnd: isize, nindex: i32) -> isize;
        fn SetWindowLongPtrW(hwnd: isize, nindex: i32, dwnewlong: isize) -> isize;
    }
    if let Ok(hwnd) = window.hwnd() {
        unsafe {
            let h = hwnd.0 as isize;
            let style = GetWindowLongPtrW(h, GWL_STYLE);
            SetWindowLongPtrW(h, GWL_STYLE, style & !WS_MAXIMIZEBOX);
        }
    }
}

pub fn run() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![commands::gateway_info])
        .setup(|app| {
            // The HUD itself hosts the local gateway (design.md §5.1); no broker process
            server::spawn(app.handle().clone());
            // The config-defined window already exists before setup; opt it out of Aero Snap
            #[cfg(windows)]
            if let Some(w) = app.get_webview_window("main") {
                disable_aero_snap(&w);
            }
            // No quit button on the frame (borderless, no taskbar icon): the tray menu is the exit.
            // Icon generated by scripts/gen-icon.mjs, embedded as raw pixels at compile time.
            let reset = MenuItem::with_id(app, "reset-pos", "重置窗口位置", true, None::<&str>)?;
            let quit = MenuItem::with_id(app, "quit", "退出 ath-hud", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&reset, &quit])?;
            TrayIconBuilder::new()
                .icon(tauri::include_image!("icons/tray.png"))
                .tooltip("ath-hud —— agent 会话悬浮窗")
                .menu(&menu)
                .show_menu_on_left_click(false)
                .on_menu_event(|app, event| match event.id().as_ref() {
                    "quit" => app.exit(0),
                    // Window geometry (collapse/dock side/strip size) lives in the frontend; just emit
                    "reset-pos" => {
                        if let Some(w) = app.get_webview_window("main") {
                            let _ = w.emit("ath-hud-reset-position", ());
                        }
                    }
                    _ => {}
                })
                .build(app)?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running ath-hud");
}
